language: python
python:
- 2.7
install:
- echo $TRAVIS_PULL_REQUEST
- NOTEBOOKS="science/Transients/"
- d=`TZ=":US/Pacific" date +%y-%m-%d----%H:%M:%S`
script:
- echo $PWD
- echo `ls ./scripts/`
- df -kh .
- wget https://raw.githubusercontent.com/marcusbooyah/IPy-CI/master/scripts/dl.sh
  -P ./scripts
- echo `ls ./scripts/`
- source ./scripts/dl.sh
- source ./scripts/prepare.sh
- export PATH="$PWD/miniconda/bin:$PATH"
- source ./scripts/sims_maf_setup.sh
- source ./scripts/getfiles.sh
- source ./scripts/sims_maf_data.sh
- source ./scripts/runipy.sh
after_deploy:
- exit $ERROR
deploy:
  provider: s3
  access_key_id: AKIAIYCAQSKSL463N6ZA
  secret_access_key:
    secure: fZSbF9uCtfT71Sh/1R9OpdeF87IXPAKHKdsNL7iQWkgAif/c5zwxU+8potzfSgT5E4FpYJtQisxxnfG3GTFZaELp+XwlRRGDdF6gO2C0BbwXqyPsVHNNru111r0kSb/cv/EYGNauMF7k+P8zNZ3At3aDyZ7NuKn4xh9CefQIPCo=
  bucket: rbiswasmaf
  local-dir: fails
  upload-dir: '"$d"'
  on:
    repo: rbiswas4/sims_maf_contrib
    branch: ci-noPR
